version: "3.9"
services:
  backend:
    build:
      context: ./weleadco
    env_file:
      - ./.env
    ports:
      - "8013:8080"
  db:
    image: postgres:12.9-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8011:8080

